# Multi-stage production image: Astro (Bun adapter) + PM2 (pm2-runtime as PID 1)
# https://docs.docker.com/guides/nodejs/containerize/
ARG BUN_VERSION=1.2
FROM oven/bun:${BUN_VERSION}-alpine AS deps
WORKDIR /app
ENV HUSKY=0
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM deps AS build
COPY . .
ARG PUBLIC_SITE_URL
ARG PUBLIC_MEDIA_SPLASH_SOURCE_TYPE
ARG PUBLIC_MEDIA_SPLASH_BASE_URL
ARG MEDIA_SPLASH_LOCAL_FOLDER_PATH
ARG PUBLIC_MEDIA_SPLASH_PATTERNS
ARG PUBLIC_MEDIA_SCREENSHOT_SOURCE_TYPE
ARG PUBLIC_MEDIA_SCREENSHOT_BASE_URL
ARG MEDIA_SCREENSHOT_LOCAL_FOLDER_PATH
ARG PUBLIC_MEDIA_SCREENSHOT_PATTERNS
ARG PUBLIC_MEDIA_SOURCE_TYPE
ARG PUBLIC_MEDIA_BASE_URL
ARG MEDIA_LOCAL_FOLDER_PATH
ARG PUBLIC_MEDIA_MAX_IMAGES_PER_CATEGORY
ARG MEDIA_CACHE_DURATION
ARG PUBLIC_YOUTUBE_PLAYLIST_ID
ARG PUBLIC_YOUTUBE_PLAYLIST_URL
ARG PUBLIC_YOUTUBE_API_KEY
ARG PUBLIC_YOUTUBE_DEFAULT_SONG_INDEX
ENV NODE_ENV=production \
	PUBLIC_SITE_URL=${PUBLIC_SITE_URL} \
	PUBLIC_MEDIA_SPLASH_SOURCE_TYPE=${PUBLIC_MEDIA_SPLASH_SOURCE_TYPE} \
	PUBLIC_MEDIA_SPLASH_BASE_URL=${PUBLIC_MEDIA_SPLASH_BASE_URL} \
	MEDIA_SPLASH_LOCAL_FOLDER_PATH=${MEDIA_SPLASH_LOCAL_FOLDER_PATH} \
	PUBLIC_MEDIA_SPLASH_PATTERNS=${PUBLIC_MEDIA_SPLASH_PATTERNS} \
	PUBLIC_MEDIA_SCREENSHOT_SOURCE_TYPE=${PUBLIC_MEDIA_SCREENSHOT_SOURCE_TYPE} \
	PUBLIC_MEDIA_SCREENSHOT_BASE_URL=${PUBLIC_MEDIA_SCREENSHOT_BASE_URL} \
	MEDIA_SCREENSHOT_LOCAL_FOLDER_PATH=${MEDIA_SCREENSHOT_LOCAL_FOLDER_PATH} \
	PUBLIC_MEDIA_SCREENSHOT_PATTERNS=${PUBLIC_MEDIA_SCREENSHOT_PATTERNS} \
	PUBLIC_MEDIA_SOURCE_TYPE=${PUBLIC_MEDIA_SOURCE_TYPE} \
	PUBLIC_MEDIA_BASE_URL=${PUBLIC_MEDIA_BASE_URL} \
	MEDIA_LOCAL_FOLDER_PATH=${MEDIA_LOCAL_FOLDER_PATH} \
	PUBLIC_MEDIA_MAX_IMAGES_PER_CATEGORY=${PUBLIC_MEDIA_MAX_IMAGES_PER_CATEGORY} \
	MEDIA_CACHE_DURATION=${MEDIA_CACHE_DURATION} \
	PUBLIC_YOUTUBE_PLAYLIST_ID=${PUBLIC_YOUTUBE_PLAYLIST_ID} \
	PUBLIC_YOUTUBE_PLAYLIST_URL=${PUBLIC_YOUTUBE_PLAYLIST_URL} \
	PUBLIC_YOUTUBE_API_KEY=${PUBLIC_YOUTUBE_API_KEY} \
	PUBLIC_YOUTUBE_DEFAULT_SONG_INDEX=${PUBLIC_YOUTUBE_DEFAULT_SONG_INDEX}
RUN bun run build

FROM oven/bun:${BUN_VERSION}-alpine AS production
WORKDIR /app
RUN apk add --no-cache curl \
	&& addgroup -g 1001 -S splurt \
	&& adduser -S -u 1001 -G splurt splurt

ENV NODE_ENV=production

COPY --from=deps --chown=splurt:splurt /app/node_modules ./node_modules
COPY --from=build --chown=splurt:splurt /app/dist ./dist
COPY --chown=splurt:splurt package.json bun.lock ecosystem.config.cjs ./

RUN mkdir -p logs && chown splurt:splurt logs

USER splurt
EXPOSE 4321

# PORT can be overridden via env; shell form reads it at check time
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
	CMD sh -c 'curl -fsS "http://127.0.0.1:$${PORT:-4321}/" -o /dev/null || exit 1'

# pm2-runtime keeps the process in the foreground (required for containers)
CMD ["bun", "run", "start:docker"]
